version: "3.8"

services:
  cadmium-cloud:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cadmium-cloud
    restart: always
    ports:
      - "8080:8080"
    environment:
      - RUST_LOG=info 
      - MONGODB_URI=mongodb://mongodb:27017/cadmium-cloud # Updated for local container MongoDB connection
      - MONGODB_DB=cadmium-cloud
    depends_on:
      mongodb:
        condition: service_healthy # Wait for MongoDB to be ready

  mongodb:
      image: mongo:latest
      container_name: mongodb
      restart: always
      ports:
        - "27017:27017"
      volumes:
        - ./mongod.conf:/etc/mongod.conf:ro
      command: ["mongod", "--config", "/etc/mongod.conf"]
      ulimits:
        nofile:
          soft: 64000
          hard: 64000
      deploy:
        resources:
          limits:
            cpus: '3'
            memory: 16G
          reservations:
            cpus: '2'
            memory: 12G
      healthcheck:
        test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
        interval: 10s
        timeout: 10s
        retries: 3




volumes:
  mongodb-data:
    driver: local
