version: "3.8"

services:
  cadmium-cloud:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cadmium-cloud
    restart: always
    ports:
      - "8080:8080"
    environment:
      - RUST_LOG=info 
      - MONGODB_URI=mongodb://mongodb:27017/cadmium-cloud # Updated for local container MongoDB connection
      - MONGODB_DB=cadmium-cloud
    depends_on:
      mongodb:
        condition: service_healthy # Wait for MongoDB to be ready
    ulimits:
      nofile: 65535 # Increase file descriptors for Rust app

  mongodb:
    image: mongo:6
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=cadmium-cloud
    healthcheck: # Ensures MongoDB is ready before dependent services start
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5
    ulimits:
      nofile: 65535 # Increase file descriptors for MongoDB

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      cadmium-cloud:
        condition: service_started # Wait for Rust app to start

volumes:
  mongodb-data:
    driver: local
