version: "3.8"

services:
  cadmium-cloud:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cadmium-cloud
    restart: always
    ports:
      - "8080:8080"
    environment:
      - RUST_LOG=info 
      - MONGODB_URI=mongodb://mongodb:27017/cadmium-cloud # Updated for local container MongoDB connection
      - MONGODB_DB=cadmium-cloud
    depends_on:
      mongodb:
        condition: service_healthy # Wait for MongoDB to be ready

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
      - mongodb-logs:/data/log
      - ./mongod.conf:/etc/mongod.conf:ro
    command: ["mongod", "--config", "/etc/mongod.conf"]
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 10s
      retries: 5

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      cadmium-cloud:
        condition: service_started # Wait for Rust app to start

volumes:
  mongodb-data:
    driver: local
  mongodb-logs:
    driver: local
