version: "3.8"

services:
  cadmium-cloud:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cadmium-cloud
    restart: always
    ports:
      - "8080:8080"
    environment:
      - RUST_LOG=info 
      - MONGODB_URI=mongodb://mongodb:27017/cadmium-cloud # Updated for local container MongoDB connection
      - MONGODB_DB=cadmium-cloud
    depends_on:
      mongodb:
        condition: service_healthy # Wait for MongoDB to be ready

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    healthcheck: # Ensures MongoDB is ready before dependent services start
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 10s
      retries: 5

  haproxy:
    image: haproxy:latest
    container_name: haproxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      cadmium-cloud:
        condition: service_started # Wait for Rust app to start

volumes:
  mongodb-data:
    driver: local
